### PR TITLE
Improvement/update of HyQ

### PR DESCRIPTION
**Pull request by pFernbach**

### CODE REVIEW

**Comment by nim65s** [comment]
This is OK on my side :)

**Comment by nim65s** [comment]
Can we merge before the release ?

**Comment by stonneau** [comment]
I am a bit late but why did the size of the feet need to be changed ?

**Comment by pFernbach** [comment]
I had weird numerical errors in TSID with a contact surface of only 1cm of radius and I was in a hurry to produce a demo. I will try to fix this issue and revert the value after that.

**Pull request merged**
